- judger-backend/judger/base.js
c언어에서 math.h헤더를 사용할 때 발생하는 컴파일 오류를 해결
11번째 줄 뒤에 -lm을 추가함
> c언어 math.h 사용시 오류 해결

- judger-backend/judger-api/errors/index.js
- judger-backend/judger-api/models/@main/schemas/contest.schema.js
- judger-backend/judger-api/routes/api/v1/contest/controller.js
- judger-backend/judger-api/routes/api/v1/contest/index.js
- judger-frontend/projects/main/src/app/constants/error-codes.ts
- judger-frontend/projects/main/src/app/pages/contest-pages/contest-problem-list-page/contest-problem-list-page.component.html
- judger-frontend/projects/main/src/app/pages/contest-pages/contest-problem-list-page/contest-problem-list-page.component.ts
- judger-frontend/projects/main/src/app/services/apis/contest.service.ts
대회 나가기 버튼을 누른다면 대회 진행중 다시 접근 불가능
contest의 db 구조 변경도 추가 -> 유저 현재 상태(나가기) 확인을 위함
> Exit contest block reentry feature

- judger-backend/judger-api/constants/index.js
- judger-backend/judger-api/routes/api/v1/notice/controller.js
- judger-backend/judger-api/routes/api/v1/notice/index.js
자신이 작성한 공지사항의 글은 get 요청  /notice/me로 호출 가능합니다
공지사항에서도 이미지를 사용할때 로컬에 저장된 이미지의 주소를 db에 저장하는 코드를 추가했습니다
> 공지사항 자신이 작성한 글 출력 api, 공지사항 이미지 주소 DB추가

- judger-backend/judger-api/routes/api/v1/practice/controller.js
- judger-backend/judger-api/routes/api/v1/practice/index.js
> Feat: 연습문제 예제파일 api 추가

- judger-backend/judger-api/routes/api/v1/search/controller.js
- judger-backend/judger-api/routes/api/v1/search/index.js
사용자가 만든 문제 검색(리스트) localhost:4003/v1/search?title=x
사용자가 만든 문제 (디테일) localhost:4003/v1/search/6722fc14e03947002d70758f/
디테일 페이지에서 파일 다운로드 localhost:4003/v1/search/6722fc14e03947002d70758f/6722fc04e03947002d70758c
search/문제id/파일id 형식입니다
> Feature/search problems 사용자가 만든 문제 검색(title) 및 pdf,입출력 파일, 예제 파일 다운로드 기능

- judger-frontend/app/contests/[cid]/components/ContestContestContestantList.tsx
- judger-frontend/app/contests/[cid]/components/ContestContestantListItem.tsx
- judger-frontend/app/contests/[cid]/components/EmptyContestContestantListItem.tsx
resolve #26 
대회 상세 페이지 내 참가자 테이블 UI를 변경하였습니다.
> chore: 대회 상세 페이지 내 참가자 테이블 UI 변경

- judger-frontend/app/contests/[cid]/problems/register/multiple/page.tsx
- judger-frontend/app/exams/[eid]/problems/register/multiple/page.tsx
- judger-frontend/app/practices/register/multiple/page.tsx
- judger-frontend/next.config.js
resolve #32 
module not found 및 dropzone hook 에러를 제거했습니다.
> fix: module not found 및 dropzone hook 에러 제거

- judger-frontend/app/components/Navbar.tsx
resolve #51 
홈페이지 최상단에 위치하는 Navbar의 너비를 브라우저의 너비에 맞게 동적으로 조절되는
기존 로직에서 높이 설정 및 너비 값을 일부 수정했습니다.
> chore: Navbar 동적 너비 설정 변경

- judger-frontend/app/components/Footer.tsx
- judger-frontend/app/components/Navbar.tsx
- judger-frontend/app/contests/[cid]/edit/page.tsx
- judger-frontend/app/contests/[cid]/problems/[problemId]/edit/page.tsx
- judger-frontend/app/contests/[cid]/problems/register/page.tsx
- judger-frontend/app/contests/[cid]/submits/page.tsx
- judger-frontend/app/contests/page.tsx
- judger-frontend/app/contests/register/page.tsx
- judger-frontend/app/exams/[eid]/edit/page.tsx
- judger-frontend/app/exams/[eid]/problems/[problemId]/edit/page.tsx
- judger-frontend/app/exams/[eid]/problems/register/page.tsx
- judger-frontend/app/exams/[eid]/submits/page.tsx
- judger-frontend/app/exams/page.tsx
- judger-frontend/app/exams/register/page.tsx
- judger-frontend/app/login/page.tsx
- judger-frontend/app/mypage/components/MyPagelayoutLoadingSkeleton.tsx
- judger-frontend/app/mypage/layout.tsx
- judger-frontend/app/notices/[nid]/edit/page.tsx
- judger-frontend/app/notices/page.tsx
- judger-frontend/app/notices/register/page.tsx
- judger-frontend/app/page.tsx
- judger-frontend/app/practices/[pid]/edit/page.tsx
- judger-frontend/app/practices/page.tsx
- judger-frontend/app/practices/register/page.tsx
resolve #55 
홈페이지 내 일부 UI 스타일을 일괄적으로 변경했습니다.
> chore: 홈페이지 일부 UI 스타일 일괄 변경

- judger-frontend/app/contests/[cid]/edit/page.tsx
- judger-frontend/app/contests/[cid]/problems/[problemId]/edit/components/searchedProblem/SearchedProblemList.tsx
- judger-frontend/app/contests/[cid]/problems/[problemId]/edit/page.tsx
- judger-frontend/app/contests/[cid]/problems/[problemId]/submit/page.tsx
- judger-frontend/app/contests/[cid]/problems/[problemId]/submits/[submitId]/page.tsx
- judger-frontend/app/contests/[cid]/problems/[problemId]/submits/page.tsx
- judger-frontend/app/contests/[cid]/problems/register/components/searchedProblem/SearchedProblemList.tsx
- judger-frontend/app/contests/[cid]/problems/register/multiple/page.tsx
- judger-frontend/app/contests/[cid]/problems/register/page.tsx
- judger-frontend/app/contests/[cid]/ranklist/page.tsx
- judger-frontend/app/contests/[cid]/submits/[submitId]/page.tsx
- judger-frontend/app/contests/[cid]/submits/page.tsx
- judger-frontend/app/exams/[eid]/edit/page.tsx
- judger-frontend/app/exams/[eid]/problems/[problemId]/edit/components/searchedProblem/SearchedProblemList.tsx
- judger-frontend/app/exams/[eid]/problems/[problemId]/edit/page.tsx
- judger-frontend/app/exams/[eid]/problems/[problemId]/submit/page.tsx
- judger-frontend/app/exams/[eid]/problems/[problemId]/submits/[submitId]/page.tsx
- judger-frontend/app/exams/[eid]/problems/[problemId]/submits/page.tsx
- judger-frontend/app/exams/[eid]/problems/register/components/searchedProblem/SearchedProblemList.tsx
- judger-frontend/app/exams/[eid]/problems/register/multiple/page.tsx
- judger-frontend/app/exams/[eid]/problems/register/page.tsx
- judger-frontend/app/exams/[eid]/submits/[submitId]/page.tsx
- judger-frontend/app/exams/[eid]/submits/page.tsx
- judger-frontend/app/notices/[nid]/edit/page.tsx
- judger-frontend/app/practices/[pid]/edit/components/searchedProblem/SearchedProblemList.tsx
- judger-frontend/app/practices/[pid]/submits/[submitId]/page.tsx
- judger-frontend/app/practices/register/components/searchedProblem/SearchedProblemList.tsx
resolve #59 
웹 서비스 내에 존재하는 모든 목록 페이지 내에 반응형 웹 스타일
코드를 추가하여 모바일 환경에서도 해당 페이지에 접근했을 때
적절한 레이아웃 크기로 서비스를 이용할 수 있도록 했습니다.
> fix: 모든 목록 페이지 내 반응형 웹 스타일 코드 추가

- judger-frontend/app/mypage/layout.tsx
- judger-frontend/app/mypage/profile/page.tsx
resolve #61 
마이페이지 내 RWD를 적용하여 모바일 기기에서도 적합한 형태의
페이지 레이아웃을 제공하여 UX를 높이고자 했습니다.
- `RWD` 적용 전 마이페이지 화면
- `RWD` 적용 후, 마이페이지 화면
> feat: 마이페이지 내 RWD 적용

- judger-frontend/app/components/Navbar.tsx
- judger-frontend/app/globals.css
resolve #65 
Navbar 컴포넌트의 스타일을 변경하여 UX를 향상시키고자
하였습니다.
- 변경 전 `Navbar` UI
- 변경 후 `Navbar` UI
> chore: Navbar 컴포넌트 스타일 변경

- judger-frontend/app/page.tsx
resolve #69 
메인페이지 내 대표 이미지에 맞춰 페이지 UI를 일부 수정했습니다.
- `Before`
- `After`
> chore: 메인페이지 UI 변경

- .github/workflows/ci-cd.yml
resolve #80 
GitHub 캐시 서버를 이용하여 CI 중에 의존성 데이터를 캐시로 사용하여
CI 시간을 단축하고자 하였습니다.
1. `1m 53s` / 9m 10s
2. `1m 55s` / 8m 50s
3. `1m 53s` / 9m 20s
1. `1m 30s` / 8m 33s
2. `1m 27s` / 8m 51s
3. `1m 29s` / 8m 44s
> CI 시간 22% 단축
> feat: CI 프로세스 내 의존성 캐시 적용

- judger-frontend/jest.config.ts
- judger-frontend/jest.setup.ts
- judger-frontend/package-lock.json
- judger-frontend/package.json
- judger-frontend/yarn.lock
resolve #84 
`judger-frontend` 디렉토리 내 존재하는 코드에 대해 단위 및 통합 테스트를 위해
jest 프레임워크를 추가하고자 하였습니다.
> feat: Jest 프레임워크 사용을 위한 config 및 setup 파일 추가

- judger-frontend/next.config.js
- judger-frontend/package-lock.json
- judger-frontend/package.json
- judger-frontend/yarn.lock
resolve #85 
프론트 측 프로젝트의 번들 크기 분석을 위해 `bundle-analyzer` 추가했습니다.
> feat: Bundle 크기 분석을 위한 bundle-analyzer 추가

- judger-frontend/next-sitemap.config.js
- judger-frontend/package-lock.json
- judger-frontend/package.json
- judger-frontend/public/robots.txt
- judger-frontend/public/sitemap-0.xml
- judger-frontend/public/sitemap.xml
- judger-frontend/yarn.lock
resolve #88 
모든 검색 엔진 크롤러 사용 및 사이트의 SEO 사용을 위해 `sitemap.xml` 파일과,
`robots.txt` 파일을 추가했습니다.
> feat: SEO 사용을 위한 sitemap.xml 및 robots.txt 파일 추가

- .github/workflows/ci.yml
resolve #90 
PR 생성 시 브랜치에 추가된 이력에 대한 CI 체크를 위해 PR 전용
CI 워크플로우를 추가하고자 하였습니다.
> feat: PR 생성 시 커밋에 대한 CI 체크를 위한 워크플로우 추가

- .github/workflows/ci-cd.yml
- judger-frontend/app/components/Navbar.tsx
- judger-frontend/app/layout.tsx
- judger-frontend/public/sitemap-0.xml
- judger-frontend/public/sitemap.xml
resolve #92 
Naver 검색 포털 내 서비스명 검색 시에 서비스가 검색 결과에 포함될 수 있도록
`Naver Search Advisor` 등록을 진행합니다
- Navbar 테마 변경 스크롤 위치 조정
> feat: Naver Search Advisor 등록을 위한 프로젝트 meta 데이터 수정

- judger-frontend/app/contests/[cid]/problems/components/ContestProblemList.tsx
- judger-frontend/app/exams/[eid]/problems/components/ExamProblemList.tsx
- judger-frontend/app/globals.css
- judger-frontend/next.config.js
- judger-frontend/package-lock.json
resolve #108 
`react-beautiful-dnd` 라이브러리를 사용하여 대회 및 시험 내 문제 목록 페이지에서 문제 순서를 변경할 때 사용하던 Drag&Drop 기능을 사용할 수 없다는 것을 확인하여 이를 해결하여 Drag&Drop 기능이 정상적으로 작동될 수 있도록 하였습니다.
> fix: react-beautiful-dnd 라이브러리를 이용한 기존 Drag&Drop 기능 사용 불가 이슈 해결
